### ISSUE TITLE
Is there any ECB-specific help channel / mailing list / etc?

### ISSUE THREAD

**Issue by jsyjr** [ecb-home/ecb#12]

**Comment by johnbendi** [comment]
None that I know of. But if you have any minor questions you can start by asking it here since there are no major support channels available at this time let's use this avenue to get help. That's what I'm going to do anyway.

**Comment by johnbendi** [comment]
Oops! I just discovered there is one but not very active: http://sourceforge.net/p/ecb/mailman/ecb-list/

**Comment by ware** [comment]
Yes, it is not very active.  However, we'll be making sure that there is more activity here.

**Comment by ware** [comment]
@jsyjr, I'm going to be closing this issue.  If you feel it shouldn't be, please reopen it.  That said, please feel free to open new questions here as you have them.

**Comment by pwojnowski** [comment]
Yo! 
I've been reading a lot on the subject we were discussing  in  our last conversation and found a lot of interesting moments, read more here <http://real.customclosets952.com/e4dpipvp>
Be well, esperanto


71881
