### ISSUE TITLE
Clarify package status in README

### ISSUE THREAD

**Issue by dakrone** [ecb-home/ecb#17]
The current readme states:

> The latest version can be found at: http://ecb.sourceforge.net

However, it looks like ECB has moved to Github?

Can the README be clarified for where to get the latest code (the package on MELPA points to Alex Ott's fork, is that the canonical version?) and what the status of ECB is? (dead/alive/abandoned)

**Comment by ware** [comment]
I'll update it.  The Sourceforge is dead.  I'll be updating MELPA in the near future.

**Comment by dakrone** [comment]
No problem, thanks for the update, hope you are feeling better now!

**Comment by ware** [comment]
I'm doing better.  Just updated this with commit b903385.

**Comment by dakrone** [comment]
@ware awesome, thanks! Now that the changes from Alex Ott are merged in, should the MELPA recipe be changed to point here instead of to his fork?

**Comment by ware** [comment]
It will be.  :-)
