### ISSUE TITLE
ecb directories buffer does not show nodes with names of less than 3 characters

### ISSUE THREAD

**Issue by johnbendi** [ecb-home/ecb#23]
I have been wondering why certain directories in my source tree does not show up in the directories buffer until I discovered that directories with names of 2 characters or less are filtered out. I have tried to search the ecb customization group for a customization setting that controls this behavior to no avail. 

Please confirm if this is the case at your end and suggest a way around this behavior.

Regards

**Comment by ware** [comment]
Let me look into it.

**Comment by ware** [comment]
@johnbendi, are you still seeing this behavior?  I just tried to reproduce this and am not seeing this behavior.  What I see is:
```
 |  |  |  | [+]LJS
 |  |  |  | [-]te
 |  |  |  |  | [x]a
 |  |  |  |  | [x]ab
 |  |  |  |  | [x]b
 |  |  |  |  | [x]dist
 |  |  |  |  | [x]es6
 |  |  |  |  | [+]node_modules
 |  |  |  |  `-[+]public
```
Those are directories with only 1 and 2 characters.  Is this what you're talking about or is there something I'm missing?

**Comment by johnbendi** [comment]
@ware I have resolved the issue. It was caused by a `ecb-excluded-directories-regexps` setting where I tried to show all hidden folders but exclude the `.` and `..` directories using a single regexp, but the regexp ended up excluding all directories with one or two letters. I achieved my objective by using two separate regexp entries to that variable. Let me know if you need more detail. Thanks.
