### ISSUE TITLE
Error messages loading ECB

### ISSUE THREAD

**Issue by cneira** [ecb-home/ecb#32]
These error messages are present when loading ecb.el

Loading ecb.el (source)...
Compiler-macro error for cl-typep: (error "Unknown type button-release-event")
Compiler-macro error for cl-typep: (error "Unknown type button-press-event")
ECB 2.50 uses CEDET 2.0 (contains semantic 2.2, eieio 1.4, speedbar <unknown version>).
Compiler-macro error for cl-typep: (error "Unknown type button-release-event")
Compiler-macro error for cl-typep: (error "Unknown type button-press-event")
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el: Missing value for option `t' of slot `modeline-menu-creator' in struct tree-buffer-spec!
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el:   I'll take `:read-only' to be an option rather than a default value.
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el: Missing value for option `t' of slot `sticky-parent-p' in struct tree-buffer-spec!
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el:   I'll take `:read-only' to be an option rather than a default value.
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el: Missing value for option `t' of slot `sticky-indent-string' in struct tree-buffer-spec!
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el:   I'll take `:read-only' to be an option rather than a default value.
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el: Missing value for option `t' of slot `sticky-parent-fn' in struct tree-buffer-spec!
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el:   I'll take `:read-only' to be an option rather than a default value.
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el: Missing value for option `t' of slot `reduce-tree-for-incr-search-fn' in struct tree-buffer-spec!
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/tree-buffer.el:   I'll take `:read-only' to be an option rather than a default value.
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/ecb-navigate.el: Obsolete name arg "node" to constructor ecb-dlist-node
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/ecb-navigate.el: Obsolete name arg "First item" to constructor ecb-nav-history-item
../../../../Users/a03550a/AppData/Roaming/.emacs.d/ecb/ecb-navigate.el: Obsolete name arg "First item" to constructor ecb-nav-history-item
Loading c:/Users/a03550a/AppData/Roaming/.emacs.d/ecb/ecb.el (source)...done

I'm using ecb from git.

**Comment by pwojnowski** [comment]
Which Emacs versions you are using? To me it looks like issue in Emacs 25 - we had this here: https://github.com/jdee-emacs/jdee/issues/82
